package nuclearscience;

import org.apache.logging.log4j.Logger;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import nuclearscience.block.NuclearScienceBlocks;
import nuclearscience.tab.CreativeTabNuclearScience;
import nuclearscience.util.GuiHandler;

@Mod(modid = "IC2NuclearScience", name = "", version = "", dependencies = "required-after:IC2@2.2.828")
public class NuclearScience {
	
	@Instance
	public static NuclearScience instance;
	
	public static Logger logger;
	
	public static final CreativeTabNuclearScience tab = new CreativeTabNuclearScience();

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		logger = event.getModLog();
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
	}
	
	@Mod.EventHandler
	public void init(FMLPreInitializationEvent event) {
		NuclearScienceBlocks.registerBlocks();
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, new GuiHandler());
	}

	@Mod.EventHandler
	public void postInit(FMLPreInitializationEvent event) {

	}
	
	public static void log(String message) {
		logger.info(message);
	}
	
	public static void error(String message) {
		logger.error(message);
	}
	
	public static void warn(String message) {
		logger.warn(message);
	}

}
